### ISSUE TITLE
Logs are not working

### ISSUE THREAD

**Issue by waltervargas** [UlricE/pen#21]
Hi, 

I am using the next command (as root): 

`/usr/local/bin/pen -l /var/log/pen.log -f -U 30089 10.x.x.2x:30089`

And the file  `/var/log/pen.log` is empty. 

I am doing something wrong ? 

Thanks in advance.

**Comment by UlricE** [comment]
The log is meant for http requests. It logs the client ip, timestamp, server ip and the request. The purpose of the log is to consolidate Apache web server logs by correlating Pen's logs with Apache's, especially useful together with penlog. UDP requests are never logged. I would use tcpdump or wireshark for that.

If you want to log diagnostics, they are sent to the console (stderr) if running in the foreground, otherwise to syslog. You need at least one -d to get diagnostics and I usually recommend that, otherwise Pen may fail silently.

**Comment by waltervargas** [comment]
Thanks for your answer @UlricE. I will use tcpdump. 

Regards.

**Comment by UlricE** [comment]
Closing since tcpdump is a suitable way to log udp traffic.
